version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    network_mode: bridge
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - "27017:27017"

  node_app_demo:
    build:
      context: ./app
    container_name: node_app_demo
    hostname: node_app_demo
    network_mode: bridge
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    network_mode: bridge
    ports:
      - "80:80"
    depends_on:
      - node_app_demo
    links:
      - node_app_demo
